name: Style Check

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.22

      - name: Install dependencies
        run: bun install

      - name: Check formatting and linting
        run: bun run check
